apiVersion: apps/v1
kind: Deployment
metadata:
  name: paw-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paw-server
  template:
    metadata:
      labels:
        app: paw-server
    spec:
      containers:
      - name: paw-server
        image: replaceme
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 1Gi
        ports:
        - containerPort: 5076
          name: api
        command: ["/bin/bash", "-c"]
        args: ["python natriumcast.py --host 0.0.0.0 --log-to-stdout --websocket-url ws://10.98.0.7:7074 --banano"]
        env:
          - name: REDIS_HOST
            value: redis-0.redis
          - name: REDIS_DB
            value: "15"
          - name: WORK_URL
            value: http://betsy-banano.betsy:5555
          - name: DEBUG
            value: "0"
          - name: RPC_URL
            value: http://10.98.0.7:7072
          - name: FCM_API_KEY
            valueFrom:
              secretKeyRef:
                name: paw
                key: fcm_api_key
          - name: FCM_SENDER_ID
            valueFrom:
              secretKeyRef:
                name: paw
                key: fcm_sender
